name: Uusimaa
channels:
  - conda-forge
dependencies:
  - ipywidgets>=7.5,<8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - sympy
  - xlrd
  - pyproj
  - seaborn
  - folium
  - geopandas
  - voila
